server:
  port: 8181
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.apache.catalina: DEBUG
    org.apache.coyote: DEBUG
    org.apache.tomcat: DEBUG
    org.shark.renovatio: DEBUG
