# Resilience4j configuration for COBOL migration services
resilience4j:
  circuitbreaker:
    instances:
      cobol-analysis:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      java-generation:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      migration-planning:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      plan-application:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      cobol-analysis:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 2
      java-generation:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 2
      migration-planning:
        max-attempts: 3
        wait-duration: 3s
        exponential-backoff-multiplier: 2
      plan-application:
        max-attempts: 2
        wait-duration: 5s
        exponential-backoff-multiplier: 2

  timelimiter:
    instances:
      cobol-analysis:
        timeout-duration: 30s
      java-generation:
        timeout-duration: 60s
      migration-planning:
        timeout-duration: 45s
      plan-application:
        timeout-duration: 120s

# COBOL provider specific configuration
renovatio:
  cobol:
    # Parser configuration
    parser:
      max-file-size: 10MB
      parallel-processing: true
      
    # Code generation configuration
    generation:
      target-package: org.shark.renovatio.generated.cobol
      generate-tests: true
      template-engine: freemarker
      
    # Migration configuration
    migration:
      default-strategy: incremental
      backup-original: true
      validation-enabled: true
      
    # Indexing configuration
    indexing:
      enabled: true
      max-index-size: 100MB
      rebuild-interval: 24h
      
    # Metrics configuration
    metrics:
      complexity-threshold: 10
      large-file-threshold: 1000
      
  # LLM configuration (optional)
  llm:
    enabled: false
    provider: openai
    model: gpt-3.5-turbo
    api-key: ${LLM_API_KEY:}
    max-tokens: 2048
    temperature: 0.1

# Monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: renovatio-cobol-provider

# Logging configuration
logging:
  level:
    org.shark.renovatio.provider.cobol: DEBUG
    io.github.resilience4j: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"