openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDtoGenerated'
components:
  schemas:
    UserDtoGenerated:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
